apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: mohbekmoh/kub-user:latest
          env:
            - name: AUTH_ADDRESS
              # value: localhost
              # value: 10.99.211.254
              value: "auth-service.default"
        # - name: auth
        #   image: mohbekmoh/kub-auth:latest